[env]
TERM = "alacritty"

[font]
size = 11

[window]
decorations = "full"
startup_mode = "Maximized"

[window.padding]
x = 20
y= 20
[cursor.style]
shape = "Underline"
blinking = "On"

[colors.primary]
background = '#0a0b10' # Hitam kebiruan sangat gelap
foreground = '#e0f7ff'

[colors.cursor]
text = "#1C1C1C"
cursor = "#5c9eff"

[colors.selection]
text = "#FFFFFF"
background = "#5c9eff"

[colors.normal]
black   = "#000000"
red     = "#5c9eff"
green   = "#AAAAAA"
yellow  = "#EEEEEE"
blue    = "#5c9eff"
magenta = "#F92672"
cyan    = "#DDDDDD"
white   = "#FFFFFF"
